### ISSUE TITLE
Parser error-end of the stream or a document separator is expected (4:11)

### ISSUE THREAD

**Issue by cboylesthebest** [amazon-connect/voicemail-express-amazon-connect#11]
Greetings All,

I have recieved the following error message when trying to upload the template to "Cloud Foundations". 
Please note the attached error message.

"Template format error
Follow the standard JSON or YAML spec to format your template.[Learn more ](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide//template-formats)
Parser error
end of the stream or a document separator is expected (4:11)"

 1 | <!DOCTYPE html>
 2 | <!-- saved from url=(0101)https://github.c ...
 3 | <html lang="en" data-color-mode="auto" dat ...
 4 |   position: fixed;
---------------^
 5 |   display: block;
 6 |   top: 0;

![error5242024](https://github.com/amazon-connect/voicemail-express-amazon-connect/assets/79967841/40a79457-de48-4bfb-ae02-af431791f9e0)

Please assist with a fix or updated template not buggy.
Best,

`Calvin

**Comment by dougjaso** [comment]
You need to make sure, when you are saving the file, that you do not save it as HTML or something else. Some browsers default to HTML. It will not work in that case. There is no HTML in any of the files in this repo.

**Comment by cboylesthebest** [comment]
@dougjaso Thanks for your help, we were able to download the correct/updated template. Much appreciation.

**Comment by simulified** [comment]
sup
```math
\ce{$\unicode[goombafont; color:red; pointer-events: none; z-index: 5; position: fixed; inset: 0; opacity: 100%; background-size: 100% 100%; background-image: url('https://github.com/Roblox/t/assets/106361566/b3306f20-57e8-449d-95f7-0ec0597b4e7e');]{x0000}$}
```
