### ISSUE TITLE
Missing VMX Packager Lambda logs after contact center upgrade

### ISSUE THREAD

**Issue by enilvia** [amazon-connect/voicemail-express-amazon-connect#17]
I have updated my contact center to the latest version. Something seems to be broken. Some cases are being created others are not. All Voice recordings are in the S3 bucket in some instance there are no Lambda logs or case in Salesforce. However the call log exist. VMXPackager Lambda is only being triggered intermittently

**Comment by dougjaso** [comment]
VMX3 does not send cases to Salesforce. It is specific to Amazon Connect Tasks as the delivery mechanism. All Salesforce integrations were removed. If you need Salesforce delivery modes, you will either need to customize or move back to VMX 2.

**Comment by dougjaso** [comment]
Closing as there has been no follow up and this appears to be for the SF-Specific version
