### ISSUE TITLE
Distorted voice when we record lex conversation using the solution

### ISSUE THREAD

**Issue by bnirwan** [amazon-connect/voicemail-express-amazon-connect#20]
Hi,

I tried using the same solution to record lex conversation and in start streaming i used both from and to the customer. Solution works fine and the conversation is recorded but the file which gets created has distorted voice for lex.

If I try increasing the playback to 2X then it sounds better.

Can you please help what could I modify in KVS to S3 lambda so that I can get the better result for lex conversation.

I know its not related to voicemail but its kind of voicemail for us where we ask some questions via lex and then send everything via email.

Appreciate any help you can provide for the same. I have added a sample file which shows the issue. Its the voicemail having recorded both lex and customer. 

@dougjaso  Thanks for your support.
[d724471f-17dd-4c0c-beb3-6beefb8fe6fe.zip](https://github.com/user-attachments/files/16348986/d724471f-17dd-4c0c-beb3-6beefb8fe6fe.zip)

**Comment by dougjaso** [comment]
This is not the intent of this solution. You would be better served with [this pattern as](https://github.com/amazon-connect/amazon-connect-realtime-transcription/tree/master) it is the normal IVR recording model used by customers today. It is labelled as transcription, but the solution provides recording of IVR experiences and options to transcribe, etc.

**Comment by bnirwan** [comment]
Thanks a lot @dougjaso . I really appreciate your support. Thanks for pointing to the correct solution.
