### ISSUE TITLE
KVS client not recording

### ISSUE THREAD

**Issue by jmrodz-valle** [amazon-connect/voicemail-express-amazon-connect#25]
No recording is retrieved nor sent to S3, maybe it has to do with the following error:

<html>
<body>

{     "timestamp": "2024-08-19T15:10:31Z",     "level": "DEBUG",     "message": "Response body:\nb'{\"Message\":\"End timestamp 1724080162000 is outside of the stream retention period.\"}'",     "logger": "botocore.parsers",     "requestId": "34b15189-cbd7-41e4-aefc-d09c05d83033" } | {"timestamp": "2024-08-19T15:10:31Z", "level": "DEBUG", "message": "Response body:\nb'{\"Message\":\"End timestamp 1724080162000 is outside of the stream retention period.\"}'", "logger": "botocore.parsers", "requestId": "34b15189-cbd7-41e4-aefc-d09c05d83033"}
-- | --
  | 2024-08-19T15:10:31.661Z{     "timestamp": "2024-08-19T15:10:31Z",     "level": "DEBUG",     "message": "Response headers: {'x-amzn-RequestId': '206e6e9d-1709-4558-8d8a-d345aed91dd6', 'x-amzn-ErrorType': 'InvalidArgumentException:https://kinesisvideo.amazonaws.com/doc/2017-09-30/', 'Content-Type': 'application/json', 'Content-Length': '84', 'Date': 'Mon, 19 Aug 2024 15:10:31 GMT', 'Connection': 'close'}",     "logger": "botocore.parsers",     "requestId": "34b15189-cbd7-41e4-aefc-d09c05d83033" } | {"timestamp": "2024-08-19T15:10:31Z", "level": "DEBUG", "message": "Response headers: {'x-amzn-RequestId': '206e6e9d-1709-4558-8d8a-d345aed91dd6', 'x-amzn-ErrorType': 'InvalidArgumentException:https://kinesisvideo.amazonaws.com/doc/2017-09-30/', 'Content-Type': 'application/json', 'Content-Length': '84', 'Date': 'Mon, 19 Aug 2024 15:10:31 GMT', 'Connection': 'close'}", "logger": "botocore.parsers", "requestId": "34b15189-cbd7-41e4-aefc-d09c05d83033"}
  | 2024-08-19T15:10:31.661Z{     "timestamp": "2024-08-19T15:10:31Z",     "level": "DEBUG",     "message": "Response body:\nb'{\"Message\":\"End timestamp 1724080162000 is outside of the stream retention period.\"}'",     "logger": "botocore.parsers",     "requestId": "34b15189-cbd7-41e4-aefc-d09c05d83033" } | {"timestamp": "2024-08-19T15:10:31Z", "level": "DEBUG", "message": "Response body:\nb'{\"Message\":\"End timestamp 1724080162000 is outside of the stream retention period.\"}'", "logger": "botocore.parsers", "requestId": "34b15189-cbd7-41e4-aefc-d09c05d83033"}
  | 2024-08-19T15:10:31.661Z{     "timestamp": "2024-08-19T15:10:31Z",     "level": "DEBUG",     "message": "Event needs-retry.kinesis-video-archived-media.ListFragments: calling handler <botocore.retryhandler.RetryHandler object at 0x7f5047a896a0>",     "logger": "botocore.hooks",     "requestId": "34b15189-cbd7-41e4-aefc-d09c05d83033" } | {"timestamp": "2024-08-19T15:10:31Z", "level": "DEBUG", "message": "Event needs-retry.kinesis-video-archived-media.ListFragments: calling handler <botocore.retryhandler.RetryHandler object at 0x7f5047a896a0>", "logger": "botocore.hooks", "requestId": "34b15189-cbd7-41e4-aefc-d09c05d83033"}
  | 2024-08-19T15:10:31.661Z{     "timestamp": "2024-08-19T15:10:31Z",     "level": "DEBUG",     "message": "No retry needed.",     "logger": "botocore.retryhandler",     "requestId": "34b15189-cbd7-41e4-aefc-d09c05d83033" } | {"timestamp": "2024-08-19T15:10:31Z", "level": "DEBUG", "message": "No retry needed.", "logger": "botocore.retryhandler", "requestId": "34b15189-cbd7-41e4-aefc-d09c05d83033"}
  | 2024-08-19T15:10:31.661Z{     "timestamp": "2024-08-19T15:10:31Z",     "level": "ERROR",     "message": "An error occurred (InvalidArgumentException) when calling the ListFragments operation: End timestamp 1724080162000 is outside of the stream retention period.",     "logger": "root",     "requestId": "34b15189-cbd7-41e4-aefc-d09c05d83033" } | **{"timestamp": "2024-08-19T15:10:31Z", "level": "ERROR", "message": "An error occurred (InvalidArgumentException) when calling the ListFragments operation: End timestamp 1724080162000 is outside of the stream retention period.", "logger": "root", "requestId": "34b15189-cbd7-41e4-aefc-d09c05d83033"}**
  | 2024-08-19T15:10:31.661Z{     "timestamp": "2024-08-19T15:10:31Z",     "level": "DEBUG",     "message": "********** Could not get fragment list **********",     "logger": "root",     "requestId": "34b15189-cbd7-41e4-aefc-d09c05d83033" } | {"timestamp": "2024-08-19T15:10:31Z", "level": "DEBUG", "message": "********** Could not get fragment list **********", "logger": "root", "requestId": "34b15189-cbd7-41e4-aefc-d09c05d83033"}

**Comment by dougjaso** [comment]
This message indicates that you have not set a retention period for your Kinesis VIdeo Streams. Since this is processed post-call, you need to have a minimum retention period for the streams. The lowest setting is 1 hour. Please verify the retention period.

**Comment by jmrodz-valle** [comment]
It had 1 hour retention period I just increased it to 1 year but same error still.

**Comment by dougjaso** [comment]
Was it previously set to no retention? If so, you'll notice that the existing streams will all still be set to no retention. Delete them all (from the KVS Console). then try again

**Comment by kabig** [comment]
Any update on this? I am having the same issue and same error message. Retention period is set to 24 hours (1 day), It had never been set to no retention.

**Comment by jmrodz-valle** [comment]
> @dougjaso @jmrodz-valle Any update on this? I am having the same issue and same error message. Retention period is set to 24 hours (1 day), It had never been set to no retention.

Mine was not set to "no retention" I had it first changed to 2 hours but then to 1 year for testing purposes and it started to work fine, you can also do what Jason mentions in his last comment, delete all the Streams in the Kinesis console that show 0 hours and try again.

**Comment by dougjaso** [comment]
Closing as these seem to be resolved.
