### ISSUE TITLE
Error starting KVS Stream

### ISSUE THREAD

**Issue by tdanwells** [amazon-connect/voicemail-express-amazon-connect#26]
the KVS does not want to initialize.  All the logs show is the connect log generating the following.  Where can we go to try and get more detail about the error?  The lambda functions do not appear to be called as they are not generating any cloudwatch logs.

{
    "Results": "Error",
    "ContactId": "3ef1b4bf-ac6c-47ac-96f5-d97bd1e70da6",
    "ContactFlowId": "arn:aws:connect:us-east-1:8redact:instance/5c253eredact-157607df22a8/flow-module/d81d5redact8ad8-61bf26c66547",
    "ContactFlowName": "VMX3-CoreFlowModule-ftcto9",
    "ContactFlowModuleType": "StartMediaStreaming",
    "Identifier": "Start KVS from customer only",
    "Timestamp": "2024-08-22T15:43:07.139Z",
    "Parameters": {
        "MediaStreamTypes": "Audio",
        "Track": "FromCustomer"
    },
    "ModuleExecutionStack": [
        "arn:aws:connect:us-east-1:8redact:instance/5c253e68-dd68-4credact07df22a8/flow-module/d81d572bredactc-8ad8-61bf26c66547",
        "arn:aws:connect:us-east-1:8redact:instance/5c253e68-dd68-4credactdf22a8/contact-flow/c5e59d4b-9redact8b-815c-71801be48eda"
    ]
}

**Comment by jcnovoa** [comment]
While everything else is automated, enabling KVS is a manual step you have to complete in the deployed Amazon Connect instance you are working with:
![KVS](https://github.com/user-attachments/assets/b6cc6409-0181-4660-98e6-fb3d5ef5cc91)

**Comment by dougjaso** [comment]
Can you share screenshots of the KVS config on your instance?

**Comment by AbdulQayyumaq** [comment]
Any resolution for this!

It's quite weird that i have done this for three amazon connect instances, there was no KVS initialization error for two of them but for third this start occurring.

**Comment by tdanwells** [comment]
Not yet.  Same result here.  Some instances work no problem and randomly, one that is set up the exact same will not.


From: AbdulQayyumaq ***@***.***>
Sent: Wednesday, September 4, 2024 10:17 AM
To: amazon-connect/voicemail-express-amazon-connect ***@***.***>
Cc: Wells, Dan [US-US] ***@***.***>; Author ***@***.***>
Subject: EXTERNAL: Re: [amazon-connect/voicemail-express-amazon-connect] Error starting KVS Stream (Issue #26)


CAUTION: This email originated from outside of Leidos. Be cautious when clicking or opening content.

Any resolution for this!

It's quite weird that i have done this for three amazon connect instances, there was no KVS initialization error for two of them but for third this start occurring.

**Comment by dougjaso** [comment]
If streams are not initializing, and that is what you see in logs, then there is a larger Connect/KVS issue at play and a support case needs to be opened with AWS support. To be 100% clear, the first try on a brand new instance will always fail. And if you do the second too fast, it can fail too. If you have tried and minutes later it still cannot initialize a stream, then there is a KVS/Connect problem.

**Comment by sonymammen-vf** [comment]
Same result. Tested with 2 instances.
Below screenshot summarizes all the config/results. 
![image](https://github.com/user-attachments/assets/68bc259b-ec9f-4bc4-89e4-fded185eacd1)

**Comment by dougjaso** [comment]
In your connect contact flow logs, is the stream initializing? Or is it failing?

**Comment by sonymammen-vf** [comment]
I got success in the Connect flow logs. I can see new 5 KVS streams getting created for the new tests I do. 
![image](https://github.com/user-attachments/assets/f22b4e55-61b6-4ede-9592-9895031fcaa5)

The KVStoS3 lambda is still showing as "No Records Processed" . Since that lambda is not triggered. No logs for any of the VMX3 lambdas.

**Comment by dougjaso** [comment]
So not an error in starting KVS. Error is that these are not passing through the filter. In your voicemail setup, where are you putting the process? Are you just doing the normal test flow or are you starting VM from elsewhere, like a queue flow? Can you send me an email to setup a time to troubelshoot?

**Comment by dougjaso** [comment]
This issue was caused by using a customer-provided KMS key on the Kinesis Data Stream instead of the standard AWS Provided one. CVustomer-managed key has been added to the work list for the next release.
