### ISSUE TITLE
InvalidArgumentException when Calling ListFragments Operation Due to Timestamp Being Outside Stream Retention Period

### ISSUE THREAD

**Issue by AbdulQayyumaq** [amazon-connect/voicemail-express-amazon-connect#28]
We are encountering an InvalidArgumentException error when invoking the ListFragments operation in the AWS Kinesis Video Streams API. The error message indicates that the EndTimestamp is outside the stream retention period. The Kinesis video stream retention period is configured for 1 hours.

{
"timestamp": "2024-09-04T16:03:20Z",
"level": "ERROR",
"message": "An error occurred (InvalidArgumentException) when calling the ListFragments operation: End timestamp 1725465732000 is outside of the stream retention period.",
"logger": "root",
"requestId": "bedfe797-97f6-4716-895f-db9397445794"
}

**Comment by dougjaso** [comment]
This typically is a result of the stream retention period being shorter than the execution time of the flow. What is the retention period for your KVS streams?

**Comment by AbdulQayyumaq** [comment]
Kinesis Data Streams has 1 days retention period under Data Streaming.

And Kinesis Video Streams has 1 hours under Data Storage.


And the Interesting thing is I created a new Amazon connect instance and deploy the solution with it and it works fine!


The issue is keep occurring for the desired instance.

**Comment by dougjaso** [comment]
For the instance that doesn't work, identify the stream prefix then go into kinesis video streams console and delete all of those streams. Then try again. Connect will need to rebuild the streams, so the first attempt will fail. Once you see the streams rebuilt, try again and hopefully it will work

**Comment by dougjaso** [comment]
Glad to see it is working.
