### ISSUE TITLE
VMX3-Packager fails to send task if Queue description is not set

### ISSUE THREAD

**Issue by JBTASKE** [amazon-connect/voicemail-express-amazon-connect#3]
When testing the solution, I noticed that if you do not have a queue description set for your queue the VMX3-Packager lambda errors out, and you never receive the task to your queue.

Edited to attach the file vs having the error right in the comment.

[vmx3-packager-error.txt](https://github.com/amazon-connect/voicemail-express-amazon-connect/files/15065613/vmx3-packager-error.txt)

**Comment by dougjaso** [comment]
OK. I can correct that. Its a remnant from the old version. Will update this when complete.

**Comment by dougjaso** [comment]
For now, easy fix is to add a description to the queue. There are two lines of code that need to be modified otherwise.

**Comment by JBTASKE** [comment]
Thank you,  I did add the description, and it's been working great since.

**Comment by dougjaso** [comment]
Addressed with latest update.
