### ISSUE TITLE
Issue Setting entity_email in vmx3_packager in SAML Enabled Instances

### ISSUE THREAD

**Issue by cathomas86** [amazon-connect/voicemail-express-amazon-connect#30]
Hello,

In SAML enabled Amazon Connect instances, Connect does not allow you to define the 'Email' attribute on the user, only the Secondary Email.

In the vmx3_packager, it is attempting to use the Email attribute to set the destination email address prior to calling the function to send via SES

 # Define the appropriate email target
        if writer_payload['entity_type'] == 'agent':
            try:
                entity_email = get_agent['User']['IdentityInfo']['Email']
            except: 
                entity_email = os.environ['default_email_target']

Since this doesn't exist, it will always cause it to send to the default email environmental variable.

I fixed this by editing the code to use the username instead of the Email in my case, however a more robust solution could be checking if the instance or user is SAML enabled and altering the logic here to use the SecondaryEmail attribute instead, or just use the username.

**Comment by dougjaso** [comment]
Not sure what you mean by "doesn't exist".

entity_type is determined starting at line 151 in packager. If the queue ARN contains "agent/" it is an agent queue and we set entity_type to agent on line 155.

On line 159, we retrieve the config for that agent and store it to get_agent, this includes agent email address.

So when we look for the agent email on line 254 in packager, if it is there in get_agent['User']['IdentityInfo']['Email']m we set that as the entity_email. If not, we use the default. 

THEN we pass it to the sub_ses_email code which actually does the send. 
In the case that your configuration does not use email address as the SAML identifier (Identity Center does), then you can use SecondaryEmail instead, by editing line 254 to read:

`entity_email = get_agent['User']['IdentityInfo']['SecondaryEmail']`

Hard coding is not necessary.

**Comment by cathomas86** [comment]
I'm not hard coding anything, your suggestion is exactly what I said in the original post. Are we closing this and expecting anyone using this solution to edit the code themselves, so not going to fix this overall?

**Comment by cathomas86** [comment]
Also, what I am saying is that in SAML enabled instances, you cannot define the Email (it is grayed out when creating a user). Therefore the only option is to define the SecondaryEmail, which is not what the code is attempting to retrieve currently, hence the need to modify the code in any case when using this in a SAML enabled instance, which is quite common. 
![image](https://github.com/user-attachments/assets/4cf3f6c2-67c7-4a91-af28-1babd16ae9ce)

**Comment by dougjaso** [comment]
We're releasing a new build in the next week. I have added it as a template option, which sets as an environment variable, and is pulled dynamically. Hopefully that will meet your needs.

**Comment by dougjaso** [comment]
This is in the new release. 2024.09.01
