### ISSUE TITLE
E-Mail not received 

### ISSUE THREAD

**Issue by dhesij** [amazon-connect/voicemail-express-amazon-connect#34]
From the initial CloudWatch logs i can see an email event is triggered however i'm not receiving anything. The queue has the correct tag and SES has the email address verified. Any help would be great.

**Comment by kgopelom** [comment]
You stated,  "i can an email event is triggered", do you mean the "VMX3-Packager-XXXXX" lambda function? If the lambda function prints "Email request sent" and you are receiving a 200 HTTP Status Code, then SES SendEmail API succeeded and you will have to troubleshoot from SES perspective.

You can enable [SES event publishing](https://docs.aws.amazon.com/ses/latest/dg/event-destinations-manage.html#event-destination-add) for further insights regarding Delivery issues.
