### ISSUE TITLE
Recording and transcriptions not stored in S3

### ISSUE THREAD

**Issue by jmorenogithub** [amazon-connect/voicemail-express-amazon-connect#35]
I’m seeing two errors in Cloudwatch for VMX3-KVStoS3:

•	"An error occurred (InvalidArgumentException) when calling the ListFragments operation: End timestamp 1727383921000 is outside of the stream retention period."
•	"string indices must be integers, not 'str'"

Any idea of what these errors mean and what I can do to address them?

Note: I have a Data retention period of 7 days in Kinesis.

**Comment by jmorenogithub** [comment]
After looking at issues from other users, I deleted my Kinesis Data Stream and created it again.
I also deteled the Kinesis Video Streams. The first call to Amazon Connect gave an error and generated the Video Streams. The second call went through.

However, I still can't get anything in S3 and I stop seeing anything in the /aws/lambda/VMX3-KVStoS3 log since I deleted and created again the Data Stream which is making it hard to troubleshoot.

Is it possible that the lambda function VMX3-KVStoS3 is no longer triggered? How could I fix that?

**Comment by kgopelom** [comment]
If you deleted your Kinesis Data Stream and re-created, the stream ARN might change and will need to be updated. Can you confirm if you [updated the Cloudformation Stack](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/stacksets-update.html) and changed the ARN for the Kinesis Data Stream that is configured for Contact Record streaming.

Note that if you delete a stream and Lambda fails to find a stream. After recreating the stream, you will have to re-enable the event source mapping to resume processing.

**Comment by jmorenogithub** [comment]
Hi kgopelom, I think the new Kinesis Data Stream had the same ARN, but I'm not entirely sure.
I ended up reinstalling the voicemail solution. And to be on the safe side, this time I used the version from July 2024, which I had used on another deployment. It worked well this time. Thanks.
