### ISSUE TITLE
Update Rollback Issue: Failed to Create Resource [VMXPresignerUser] in Voicemail Express Stack Update

### ISSUE THREAD

**Issue by AbdulQayyumaq** [amazon-connect/voicemail-express-amazon-connect#42]
encountering an issue while updating my Voicemail Express stack using CloudFormation. I followed the provided upgrade instructions, but the update is failing with the following error: `Embedded stack arn:aws:cloudformation:us-east-1:<AccountID>:stack/voicemail-tf-stack-abc-VMXCoreStack-5FGCN228PXIE/303XXXXX-90a3-11ef-9048-0e8XXXXXXb53 was not successfully updated. Currently in UPDATE_ROLLBACK_IN_PROGRESS with reason: The following resource(s) failed to create: [VMXPresignerUser].`

Steps to Reproduce:
> Downloaded the latest vmx3.yaml template for Voicemail Express.
> Logged in to the AWS Console and navigated to the CloudFormation console.
> Selected the correct region for my deployment.
> Chose the Voicemail Express stack and selected Update.
> Chose the option to Replace existing template, then uploaded the new template file.
> Updated the template version field to the latest version as mentioned in the instructions.
> Submitted the update request.

Expected Behavior: The update process should complete successfully, creating all required resources, and updating the stack to the latest version.

Actual Behavior: The update failed with the stack entering an UPDATE_ROLLBACK_IN_PROGRESS state. The specific resource that failed to create is [VMXPresignerUser].

**Comment by dougjaso** [comment]
Did you make sure that the version updated? At the very bottom, since the version is technically a parameter, it may keep the old version. Presigner user does not exist for certain deployment types, so it may be causeing the issue.
