### ISSUE TITLE
Wav file generated is very Choppy

### ISSUE THREAD

**Issue by bsaiteja95** [amazon-connect/voicemail-express-amazon-connect#5]
The Wav file generated from kvs-to-s3 lambda is not very clear. The audio is very Choppy. I have used the same lambda given in this repo. Any help on this is much appreciated.

I too have a sample file but i am unable to share it here.

**Comment by dougjaso** [comment]
When starting KVS, it is important that you only select "From the customer", selecting both directions will result in choppiness. Please make that change and re-test.

**Comment by bsaiteja95** [comment]
Thanks @dougjaso . That resolved my issue. I have other quick question?

In presigner lambda you have leveraged an IAM user to generate a pre-signed url. Any reason for not using IAM execution role over IAM user?

**Comment by dougjaso** [comment]
IAM User is the only entity that can presign for 7 days. 

Closing this issue. Conversation can move to discussions section if still interested.
