### ISSUE TITLE
Agent cannot open the Task.

### ISSUE THREAD

**Issue by bsaiteja95** [amazon-connect/voicemail-express-amazon-connect#8]
I am able to successfully implement the solution. I can see voicemail task is getting created. Agent (from Agent workspace & CCP) is able to see the missed task banner. But, he is unable to open the missed task to see its contents. I have a attached screenshot to this issue. I gave my agent Admin access for this testing
![Screenshot 2024-05-10 at 10 27 18 AM](https://github.com/amazon-connect/voicemail-express-amazon-connect/assets/55115574/fc958cab-93ae-49a4-8549-5e60529e4142)
.

**Comment by dougjaso** [comment]
You need to close that contact or change the concurrency settings for the agent's routing profile to allow them to handle more than 1 task simultaneously.
